DEFRA/fcp-sfd-frontend

- package-lock.json
- package.json
- src/views/errors/service-unavailable.njk
https://eaflood.atlassian.net/jira/software/projects/SFDP/boards/1959
> Change help response time from 2 days to 10 days

- package-lock.json
- package.json
- src/views/common/phase-banner/phase-banner.njk
- src/views/layout.njk
https://eaflood.atlassian.net/jira/software/projects/SFDP/boards/1959?selectedIssue=SFDP-250
Checklist :
> Add phase-banner to all pages

- package-lock.json
- package.json
- src/views/layout.njk
https://eaflood.atlassian.net/jira/software/projects/SFDP/boards/1959?selectedIssue=SFDP-229
Checklist :
> added PI charter and improved security

- package-lock.json
- package.json
- src/routes/errors/service-unavailable.js
- test/unit/routes/errors/service-unavailable.test.js
https://eaflood.atlassian.net/jira/software/projects/SFDP/boards/1959?selectedIssue=SFDP-300
> Change route description to match prototype

- package-lock.json
- package.json
- src/utils/errors.js
- src/views/home.njk
- src/views/layout.njk
- test/unit/utils/errors.test.js
https://eaflood.atlassian.net/jira/software/projects/SFDP/boards/1959?selectedIssue=SFDP-301
> added service-unavailble to error controller

- package-lock.json
- package.json
- src/routes/cookies.js
- src/routes/index.js
- src/views/common/layout.njk
- src/views/common/navigation/back-link.njk
- src/views/cookies.njk
- test/integration/narrow/routes/routes.test.js
- test/unit/routes/cookies.test.js
https://eaflood.atlassian.net/jira/software/projects/SFDP/boards/1959
Checklist :
> cookies footer element, route and view

- package-lock.json
- package.json
- src/routes/business-details/business-details.js
- src/routes/business-details/business-name-change.js
- src/routes/business-details/business-name-check.js
- src/routes/business-details/index.js
- src/views/business-details/business-details.njk
- src/views/business-details/business-name-change.njk
- src/views/business-details/business-name-check.njk
- src/views/common/layout.njk
- test/integration/narrow/routes/routes.test.js
- test/unit/routes/business-details/business-details.test.js
- test/unit/routes/business-details/business-name-change.test.js
- test/unit/routes/business-details/business-name-check.test.js
https://eaflood.atlassian.net/jira/software/projects/SFDP/boards/1959?selectedIssue=SFDP-270
Checklist :
> Sfdp 270 name check

- package-lock.json
- package.json
- src/constants/error-codes.js
- src/constants/status-codes.js
- src/constants/validation-fields.js
- src/constants/validation.js
- src/plugins/template-renderer/filters/filters.js
- src/plugins/template-renderer/filters/to-error-list.js
- src/routes/business-details/business-address-form.js
- src/routes/business-details/business-details.js
- src/routes/business-details/business-name-change.js
- src/routes/business-details/index.js
- src/schemas/business-details/business-address-form.js
- src/schemas/business-details/business-name-change.js
- src/utils/validation-error-handler.js
- src/views/business-details/business-address-form.njk
- src/views/business-details/business-details.njk
- test/integration/narrow/routes/routes.test.js
- test/unit/constants/test-addresses.js
- test/unit/plugins/template-rendering/filters/to-error-list.test.js
- test/unit/routes/business-details/business-address-form.test.js
- test/unit/routes/business-details/business-details.test.js
- test/unit/routes/business-details/business-name-change.test.js
- test/unit/utils/errors.test.js
- test/unit/utils/validation-error-handler.test.js
https://eaflood.atlassian.net/jira/software/projects/SFDP/boards/1959?selectedIssue=SFDP-286
Checklist :
> business-address-form route, view and test

- .github/CODEOWNERS
- package.json
> Switch CODEOWNERS to GitHub Team

- package.json
Bug ticket - https://eaflood.atlassian.net/browse/SFDP-363
> SFDP-363: BUG - BD21

- package.json
- src/routes/business-details/business-details.js
- src/routes/business-details/business-phone-numbers-change.js
- src/routes/business-details/business-phone-numbers-check.js
- test/unit/routes/business-details/business-details.test.js
- test/unit/routes/business-details/business-phone-numbers-check.test.js
Ticket - https://eaflood.atlassian.net/browse/SFDP-388
> SFDP-388: Bug fix for BD22 pt.2

- package.json
- src/constants/success-messages.js
- src/routes/business-details/business-address-check.js
- src/routes/business-details/business-details.js
- src/routes/business-details/business-email-check.js
- src/routes/business-details/business-name-check.js
- src/routes/business-details/business-phone-numbers-check.js
- src/views/business-details/business-details.njk
- test/unit/routes/business-details/business-details.test.js
- test/unit/routes/business-details/business-name-check.test.js
Ticket - https://eaflood.atlassian.net/browse/SFDP-387
> SFDP-387: Implement dynamic success banner

- package.json
- src/views/business-details/business-legal-status-change.njk
> bug fix of extra bracket

- README.md
- package-lock.json
- package.json
- src/config/defra-id.js
- src/config/index.js
- test/unit/config/index.test.js
> SFDP-362 DEFRA ID-fcp-sfd-frontend configuration for DefraId setup

- compose.yaml
- package.json
This PR updates the docker image for the DAL to the lastest version and includes essential ENV vars, to verify check the tests pass and that the `/example` route still returns data when running locally.
This will support upcoming development for returning data onto views.
> upgrade to latest DAL image

- package-lock.json
- package.json
- src/views/business/business-email-change.njk
- src/views/business/business-email-check.njk
- src/views/business/business-legal-status-change.njk
- src/views/business/business-name-change.njk
- src/views/business/business-name-check.njk
- src/views/business/business-phone-numbers-change.njk
- src/views/business/business-phone-numbers-check.njk
- src/views/business/business-type-change.njk
- src/views/common/navigation/back-link.njk
- src/views/cookies.njk
- src/views/footer/contact-help.njk
This PR fixes broken backlinks across the service that haven't yet been updated as part of the refactoring work. For now, most backlinks will direct users to the Business Details page. Once additional pages are built and the service's navigation is updated, these links can be revised to take users back to the appropriate previous pages.
> Fix broken back links #patch

- package-lock.json
- package.json
- src/mock-data/mock-business-details.js
- src/services/business/fetch-business-details-service.js
> Moved mockData folder from test-folder

- src/views/cookies.njk
https://eaflood.atlassian.net/browse/SFD-50
> Cookies changes

- src/views/cookies.njk
https://eaflood.atlassian.net/browse/SFD-50
> Cookie page updated to fix bugs

- src/views/business/business-address-check.njk
- src/views/business/business-address-enter.njk
- src/views/business/business-details.njk
- src/views/business/business-email-change.njk
- src/views/business/business-email-check.njk
- src/views/business/business-legal-status-change.njk
- src/views/business/business-name-change.njk
- src/views/business/business-name-check.njk
- src/views/business/business-phone-numbers-change.njk
- src/views/business/business-phone-numbers-check.njk
- src/views/business/business-type-change.njk
- src/views/common/navigation/back-link.njk
- src/views/common/navigation/back-sign-out-link.njk
- src/views/cookies.njk
- src/views/footer/accessibility-statement.njk
- src/views/footer/contact-help.njk
- src/views/personal/personal-details.njk
> Sign out link added to top bar

- src/views/cookies.njk
> Cookies changes made as per comment on ticket

- src/presenters/business/business-type-change-presenter.js
- src/routes/business/business-type-change-routes.js
- src/views/business/business-type-change.njk
- test/integration/narrow/routes/business/business-type-change-routes.test.js
- test/unit/presenters/business/business-type-change-presenter.test.js
- test/unit/routes/business/business-type-change-routes.test.js
> SFD2-148 Replace Hardcoded Business Type

- compose.override.yaml
- compose.yaml
- defra-id.data.json
> Add Defra ID stub

- src/views/home.njk
> Remove Token Information from Homepage

- README.md
- src/config/server.js
- test/unit/plugins/template-rendering/context.test.js
https://eaflood.atlassian.net/browse/SFD2-275
> Sfd2-275 Update Service Name

- src/dal/queries/business-details.js
- src/dal/queries/personal-details.js
- src/mappers/business-details-mapper.js
- src/mappers/personal-details-mapper.js
- src/mock-data/mock-business-details.js
- src/mock-data/mock-personal-details.js
- src/presenters/address-presenter.js
- src/presenters/business/business-address-enter-presenter.js
- src/schemas/business/business-address-schema.js
- src/views/business/business-address-enter.njk
- test/mocks/mock-business-details.js
- test/mocks/mock-personal-details.js
- test/unit/mappers/business-details-mapper.test.js
- test/unit/presenters/address-presenter.test.js
- test/unit/presenters/business/business-address-enter-presenter.test.js
- test/unit/presenters/business/business-details-presenter.test.js
- test/unit/presenters/personal/personal-details-presenter.test.js
- test/unit/routes/business/business-address-enter-routes.test.js
- test/unit/schemas/business/business-address-schema.test.js
- test/unit/services/business/update-business-addess-change-service.test.js
https://eaflood.atlassian.net/browse/SFD2-264
**Background**
While updating business address handling through the DAL, we found several mismatches with how version 1 (the downstream service containing the validation rules) expects addresses to be structured:
* **Lookup detection**: The business details page assumed an address was a lookup one if lookup fields were non-null. This was unreliable.
* **Postcode handling**: For manually entered addresses, we allowed postcode to be optional, but v1 requires it when no UPRN is present.
* **Manual address fields**: v1 may return a value for line3, but our UI neither displayed nor allowed editing of this field.
**Changes made**
After discussions with the DAL team and our BAs, we’ve updated the service as follows:
1) **Lookup vs manual detection** …
> Update business address page and validation

- src/presenters/signed-out-presenter.js
- test/unit/presenters/signed-out-presenter.test.js
> SFD2-275 Update Sign back in link text

- package-lock.json
- package.json
> Ran audit fix to remove vulnerability
